name: Ejecutar Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script
        run: chmod +x ./script.sh

      - name: Ejecutar script.sh
        run: ./script.sh
