name: Demo de Variables
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:                # Definir variables de entorno a nivel de job
      MY_ENV_VAR: "Hola, mundo!"
    steps:
       - name: Check out el código
         uses: actions/checkout@v3
       - name: Usar variable de entorno
         run: echo "La variable de entorno es:$MY_ENV_VAR"
       - name: Crear un archivo de texto
         run: echo "Este es un archivo generado" > output.txt
       - name: Guardar output
         id: save_output
         run: echo "output_file=$(cat output.txt)" >> $GITHUB_ENV
  deploy:
    runs-on: ubuntu-latest
    needs: build           # Este job depende del job "build"
    steps:
      - name: Check out el código
        uses: actions/checkout@v3
      - name: Leer el output del job anterior
        run: echo "El archivo generado en el job anterior es:$output_file"
      - name: Print nombre
        run: echo "Mi nombre es ${{ vars.NOMBRE }}"
