name: Descargar Artefacto

on:
  workflow_run:
    workflows: ["Subir Artefacto"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Check out el código
        uses: actions/checkout@v4

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: miartefacto

      - name: Usarlo
        run: cat output.txt
